<?xml version="1.0" ?>
<robot name="AIEdu" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find aiedu_description)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find aiedu_description)/urdf/aiedu.gazebo.xacro"/>

  <xacro:property name="r200_cam_rgb_px" value="0.005"/>
  <xacro:property name="r200_cam_rgb_py" value="0.018"/>
  <xacro:property name="r200_cam_rgb_pz" value="0.013"/>
  <xacro:property name="r200_cam_depth_offset" value="0.01"/>

  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0.0 0.0 -0.03453" rpy="0 0 ${M_PI}"/>
      <geometry>
        <mesh filename="package://aiedu_description/meshes/base/aiedu_case_asm.STL" scale="1 1 1"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 -0.003453" rpy="0 0 ${M_PI}"/>
      <geometry>
        <mesh filename="package://aiedu_description/meshes/base/aiedu_case_asm.STL" scale="1 1 1"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="-0.0426 0.0 0.0" rpy="0 0 ${M_PI}"/>
      <mass value="1"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.01" />
    </inertial>
  </link>

  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.0 0.160 0.0" rpy="0 0 ${M_PI * 0.5}"/>
    <axis xyz="1 0 0"/>
  </joint>

  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://aiedu_description/meshes/wheels/wheel.STL" scale="1 1 1"/>
      </geometry>
      <material name="dark"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://aiedu_description/meshes/wheels/wheel.STL" scale="1 1 1"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.01" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.0 -0.160 0.0" rpy="0 0 -${M_PI * 0.5}"/>
    <axis xyz="1 0 0"/>
  </joint>

  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://aiedu_description/meshes/wheels/wheel.STL" scale="1 1 1"/>
      </geometry>
      <material name="dark"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://aiedu_description/meshes/wheels/wheel.STL" scale="1 1 1"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.01" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="caster_back_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_link"/>
    <origin xyz="-0.2101 0 0.0" rpy="0 0 0"/>
  </joint>

  <link name="caster_back_link">
    <visual>
      <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.065"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.065"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.01" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.050 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

   <joint name="scan_joint" type="fixed"><!---->
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="0.075 0 0.215" rpy="0 0 0"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://aiedu_description/meshes/sensors/lds.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.0408" radius="0.070"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="ultrasonic_front_joint" type="fixed">
    <origin xyz="0.220 0.0 0.0205" rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
    <parent link="base_link"/>
    <child link="base_ultrasonic_front"/>
  </joint>

  <link name="base_ultrasonic_front">
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.020 0.005"/>
      </geometry>
      <material name="blue"/>
    </visual> 
  </link>

  <joint name="ultrasonic_left_joint" type="fixed">
    <origin xyz="0.190 +0.09 0.0205" rpy="0 0 ${M_PI/5}"/>
    <axis xyz="0 0 0"/>
    <parent link="base_link"/>
    <child link="base_ultrasonic_left"/>
  </joint>

  <link name="base_ultrasonic_left">
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.020 0.005"/>
      </geometry>
      <material name="blue"/>
    </visual> 
  </link>

  <joint name="ultrasonic_right_joint" type="fixed">
    <origin xyz="0.190 -0.09 0.0205" rpy="0 0 -${M_PI/5}"/>
    <axis xyz="0 0 0"/>
    <parent link="base_link"/>
    <child link="base_ultrasonic_right"/>
  </joint>

  <link name="base_ultrasonic_right">
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.020 0.005"/>
      </geometry>
      <material name="blue"/>
    </visual> 
  </link>

  <joint name="camera_joint" type="fixed">
    <origin xyz="0.190 -0.065 0.150" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>

  <link name="camera_link">
    <visual>
     <origin xyz="0 0 0" rpy="${M_PI*0.5} 0 ${M_PI*0.5}"/>
      <geometry>
       <mesh filename="package://aiedu_description/meshes/sensors/r200.dae" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.003 0.065 0.010" rpy="0 0 0"/>
      <geometry>
        <box size="0.008 0.130 0.022"/>
      </geometry>
    </collision>

    <!-- This inertial field needs doesn't contain reliable data!! -->
<!--   <inertial>
      <mass value="0.564" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.003881243" ixy="0.0" ixz="0.0"
               iyy="0.000498940" iyz="0.0"
               izz="0.003879257" />
    </inertial>-->
  </link>

  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_rgb_frame"/>
  </joint>
  <link name="camera_rgb_frame"/>

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_rgb_optical_frame"/>
  </joint>
  <link name="camera_rgb_optical_frame"/>

  <joint name="camera_depth_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py + r200_cam_depth_offset} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_depth_frame"/>
  </joint>
  <link name="camera_depth_frame"/>

  <joint name="camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}"/>
    <parent link="camera_depth_frame"/>
    <child link="camera_depth_optical_frame"/>
  </joint>
  <link name="camera_depth_optical_frame"/>

</robot>
